name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: primarybankcode
          POSTGRES_DB: primarybank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to become healthy..."
          until pg_isready -h localhost -p 5432 -U root; do
            echo "PostgreSQL is not ready yet. Waiting..."
            sleep 3
          done
          echo "PostgreSQL is ready!"

      - name: Verify Database Readiness
        run: |
          for i in {1..10}; do
            if PGPASSWORD=primarybankcode psql -h localhost -U root -d primarybank -c "SELECT 1"; then
              echo "✅ Database is fully ready!"
              break
            fi
            echo "⏳ Waiting for database to accept queries..."
            sleep 3
          done



      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin
          which migrate

      - name: Run Migrations
        run: make migrateup

      # - name: Test
      #   run: make test
      - name: Run a Single Test
        run: go test -run TestTransferTx -v ./...